import { Scale, AlertTriangle } from "lucide-react";

export function TermsPage() {

    return (
        <div className="min-h-screen bg-slate-50 py-12 px-6">
            <div className="max-w-3xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100">
                <div className="flex items-center gap-4 mb-8">
                    <div className="p-3 bg-blue-100 text-blue-600 rounded-2xl">
                        <Scale size={28} />
                    </div>
                    <h1 className="text-3xl font-black text-slate-900">Terms of Service</h1>
                </div>

                <div className="bg-rose-50 border border-rose-100 rounded-2xl p-5 mb-8 flex gap-4">
                    <AlertTriangle size={24} className="text-rose-600 flex-shrink-0" />
                    <div>
                        <h3 className="font-bold text-rose-900 mb-1">Strict Medical Disclaimer</h3>
                        <p className="text-rose-800 text-sm leading-relaxed">
                            I M Smrti and its AI Assistant are <strong>NOT</strong> replacements for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Do not use this application during a life-threatening medical emergency.
                        </p>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
                    <p className="font-medium text-slate-800">
                        Effective Date: May 9, 2026<br/>
                        Company Name: I M Smrti
                    </p>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing and utilizing I M Smrti, you agree to these terms. If you do not agree, please do not use the application.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">2. User Responsibilities</h2>
                        <p>You are responsible for:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li>Securing your account login credentials.</li>
                            <li>The accuracy of the medical information you upload.</li>
                            <li>Ensuring that sharing your SOS QR code is done safely, as it grants access to critical health data.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">3. AI Health Intelligence</h2>
                        <p>Our AI is based on general medical knowledge models. It can hallucinate or output inaccurate data. You MUST verify any summaries or analysis generated by the AI with a certified human doctor. The AI feature is designed to organize and summarize your own records — it does not provide diagnosis or treatment recommendations.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">4. Eligibility &amp; Family Records</h2>
                        <p>You must be at least 18 years old to create an account. When you add health records of a family member or dependent, you represent that you are their parent, legal guardian, or authorized caregiver, or that you have obtained their consent to manage their health information.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">5. Acceptable Use</h2>
                        <p>You agree not to:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li>Access or attempt to access another user's data without authorization.</li>
                            <li>Upload unlawful, malicious, or infringing content.</li>
                            <li>Reverse-engineer, scrape, overload, or interfere with the service or its security features.</li>
                            <li>Use the service to provide commercial medical services without appropriate licenses.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">6. Your Content &amp; Our Rights</h2>
                        <p>You retain ownership of the medical records and content you upload. You grant us a limited license to store, process, and display that content solely to provide the service to you. The I M Smrti name, design, and software remain our intellectual property.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">7. Service Availability &amp; Limitation of Liability</h2>
                        <p>The service is provided "as is" without warranties of uninterrupted availability. Do not rely on the app as your only copy of critical medical documents. To the maximum extent permitted by law, our total liability for any claim arising from your use of the service is limited to the amount you paid us in the 12 months preceding the claim. Nothing in these terms limits liability that cannot be limited under Indian law.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">8. Termination</h2>
                        <p>You may stop using the service and delete your account at any time from Account Settings or via <a href="/delete-account" className="font-bold text-blue-600">imsmrti.app/delete-account</a>. We may suspend or terminate accounts that violate these terms, with notice where practicable. Upon termination, your data is deleted as described in our Privacy Policy.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">9. Governing Law &amp; Grievances</h2>
                        <p>These terms are governed by the laws of India, with courts at Bhopal, Madhya Pradesh having exclusive jurisdiction. Complaints or grievances may be addressed to our Grievance Officer at <strong>hii@imsmrti.app</strong> (see the Privacy Policy for full contact details). We acknowledge grievances within 48 hours and resolve them within 30 days.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">10. Changes to These Terms</h2>
                        <p>We may update these terms from time to time. Material changes will be notified in-app or by email at least 15 days before they take effect. Continued use after the effective date constitutes acceptance.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
