import { Scale, AlertTriangle } from "lucide-react";

export function TermsPage() {

    return (
        <div className="min-h-screen bg-slate-50 py-12 px-6">
            <div className="max-w-3xl mx-auto bg-white rounded-3xl p-8 md:p-12 shadow-sm border border-slate-100">
                <div className="flex items-center gap-4 mb-8">
                    <div className="p-3 bg-blue-100 text-blue-600 rounded-2xl">
                        <Scale size={28} />
                    </div>
                    <h1 className="text-3xl font-black text-slate-900">Terms of Service</h1>
                </div>

                <div className="bg-rose-50 border border-rose-100 rounded-2xl p-5 mb-8 flex gap-4">
                    <AlertTriangle size={24} className="text-rose-600 flex-shrink-0" />
                    <div>
                        <h3 className="font-bold text-rose-900 mb-1">Strict Medical Disclaimer</h3>
                        <p className="text-rose-800 text-sm leading-relaxed">
                            I M Smrti and its AI Assistant are <strong>NOT</strong> replacements for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Do not use this application during a life-threatening medical emergency.
                        </p>
                    </div>
                </div>

                <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
                    <p className="font-medium text-slate-800">
                        Effective Date: [Insert Date]<br/>
                        Company Name: [Enter Legal Company Name]
                    </p>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing and utilizing I M Smrti, you agree to these terms. If you do not agree, please do not use the application.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">2. User Responsibilities</h2>
                        <p>You are responsible for:</p>
                        <ul className="list-disc pl-5 mt-2 space-y-2">
                            <li>Securing your account login credentials.</li>
                            <li>The accuracy of the medical information you upload.</li>
                            <li>Ensuring that sharing your SOS QR code is done safely, as it grants access to critical health data.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-slate-900 mb-3">3. AI Health Intelligence</h2>
                        <p>Our AI is based on general medical knowledge models. It can hallucinate or output inaccurate data. You MUST verify any summaries or analysis generated by the AI with a certified human doctor.</p>
                    </section>
                </div>
            </div>
        </div>
    );
}
